name: flutter_zk
description: "An unofficial library of zksoftware (zkteco family) attendance machine."
version: 1.0.3
homepage: "https://github.com/AbdullahAlMamun12/flutter_zk"
repository: "https://github.com/AbdullahAlMamun12/flutter_zk"
issue_tracker: "https://github.com/AbdullahAlMamun12/flutter_zk/issues"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_zk
      ios:
        default_package: flutter_zk
      windows:
        default_package: flutter_zk
      linux:
        default_package: flutter_zk
      macos:
        default_package: flutter_zk
